ciudad_cambiar:
    path: /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar }

ciudad_recientes:
    path: /{ciudad}/recientes
    defaults: { _controller: CiudadBundle:Default:recientes }
